import { Artwork, StudioProfile } from '../types/artwork';

export const DEFAULT_STUDIO_PROFILE: StudioProfile = {
  studioName: "Il Mio Atelier",
  artistName: "Studio d'Arte",
  city: "Firenze",
  address: "Via delle Belle Arti 12",
  email: "bottega@atelier-arte.it",
  phone: "+39 055 1234567",
  website: "www.atelier-arte.it",
  currency: "EUR",
  catalogPrefix: "OPV-"
};

export const SAMPLE_ARTWORKS: Artwork[] = [
  {
    id: "art-001",
    code: "OPV-001",
    title: "Riflessi sulla Laguna",
    artist: "Leonardo Vian",
    year: 2024,
    technique: "Olio su tela",
    support: "Telaio in lino belga",
    dimensions: { height: 70, width: 100, depth: 3 },
    framed: true,
    frameDetails: "Cornice artigianale in legno naturale",
    price: 2400,
    minPrice: 2100,
    currency: "EUR",
    status: "bottega",
    location: "Bottega - Parete Nord",
    locationNotes: "Esposto sulla parete d'ingresso",
    notes: "Studio atmosferico della luce lagunare veneziana al tramonto, con riflessi d'oro sull'acqua.",
    certificateNumber: "CERT-2024-001",
    images: [],
    createdAt: "2024-01-15T10:00:00.000Z",
    updatedAt: "2024-01-15T10:00:00.000Z"
  },
  {
    id: "art-002",
    code: "OPV-002",
    title: "Armonia Geometrica N. 4",
    artist: "Elena Moretti",
    year: 2023,
    technique: "Acrilico e pigmenti",
    support: "Tavola di pioppo preparata a gesso",
    dimensions: { height: 80, width: 80, depth: 4 },
    framed: false,
    frameDetails: "Bordi laccati a vista",
    price: 1850,
    minPrice: 1600,
    currency: "EUR",
    status: "mostra",
    location: "Galleria San Marco - Venezia",
    locationNotes: "Mostra collettiva fino al 15 Novembre",
    notes: "Composizione minimalista a campiture piatte con contrasti tonali caldi e geometrie pure.",
    certificateNumber: "CERT-2023-014",
    images: [],
    createdAt: "2023-05-10T11:30:00.000Z",
    updatedAt: "2023-05-10T11:30:00.000Z"
  },
  {
    id: "art-003",
    code: "OPV-003",
    title: "Vento d'Autunno tra i Cipressi",
    artist: "Marco Valenti",
    year: 2022,
    technique: "Tecnica mista e spatola",
    support: "Tela su telaio rinforzato",
    dimensions: { height: 60, width: 80, depth: 2.5 },
    framed: true,
    frameDetails: "Cornice scura satinata con passe-partout dorato",
    price: 1200,
    minPrice: 1000,
    currency: "EUR",
    status: "bottega",
    location: "Bottega - Cavalletto B",
    locationNotes: "In esposizione centrale",
    notes: "Scorcio toscano eseguito en plein air con pennellate dinamiche e materia corposa.",
    certificateNumber: "CERT-2022-031",
    images: [],
    createdAt: "2022-09-20T09:15:00.000Z",
    updatedAt: "2022-09-20T09:15:00.000Z"
  },
  {
    id: "art-004",
    code: "OPV-004",
    title: "Studio di nudo in penombra",
    artist: "Leonardo Vian",
    year: 2023,
    technique: "Carboncino e sanguigna",
    support: "Carta cotone 300g Fabriano",
    dimensions: { height: 70, width: 50, depth: 2 },
    framed: true,
    frameDetails: "Cornice nera a cassetta con vetro museale antiriflesso",
    price: 850,
    minPrice: 750,
    currency: "EUR",
    status: "venduto",
    location: "Collezione Privata - Milano",
    locationNotes: "Acquisito direttamente in studio",
    buyerName: "Ing. Roberto Galli",
    buyerContact: "Milano - roberto.galli@email.it",
    soldDate: "2024-03-12",
    notes: "Disegno anatomico dal vero con studio accurato del chiaroscuro e della luce radente.",
    certificateNumber: "CERT-2023-042",
    images: [],
    createdAt: "2023-11-04T15:45:00.000Z",
    updatedAt: "2024-03-12T17:00:00.000Z"
  },
  {
    id: "art-005",
    code: "OPV-005",
    title: "Metamorfosi Cosmica",
    artist: "Clara Bassi",
    year: 2024,
    technique: "Scultura in bronzo a cera persa",
    support: "Base in marmo nero del Belgio",
    dimensions: { height: 45, width: 25, depth: 20 },
    framed: false,
    frameDetails: "",
    price: 4500,
    minPrice: 4000,
    currency: "EUR",
    status: "bottega",
    location: "Bottega - Piedistallo Centrale",
    locationNotes: "Pezzo unico numerato 1/1",
    notes: "Scultura astratta che evoca il moto rotatorio delle galassie e la fluidità del metallo.",
    certificateNumber: "CERT-2024-008",
    images: [],
    createdAt: "2024-02-18T14:20:00.000Z",
    updatedAt: "2024-02-18T14:20:00.000Z"
  },
  {
    id: "art-006",
    code: "OPV-006",
    title: "Crepuscolo sul colle",
    artist: "Elena Moretti",
    year: 2023,
    technique: "Acquerello su carta Arches",
    support: "Carta cotone 640g a grana fine",
    dimensions: { height: 40, width: 55, depth: 1.5 },
    framed: true,
    frameDetails: "Cornice in rovere sbiancato con doppio passe-partout",
    price: 950,
    minPrice: 850,
    currency: "EUR",
    status: "prestito",
    location: "Pinacoteca Civica",
    locationNotes: "In prestito per la rassegna paesaggistica regionale fino a Giugno",
    notes: "Velature trasparenti con passaggi sfumati dall'arancio caldo al cobalto profondo.",
    certificateNumber: "CERT-2023-077",
    images: [],
    createdAt: "2023-07-22T08:30:00.000Z",
    updatedAt: "2023-07-22T08:30:00.000Z"
  },
  {
    id: "art-007",
    code: "OPV-007",
    title: "Canto del Mare",
    artist: "Marco Valenti",
    year: 2024,
    technique: "Olio su tela",
    support: "Telaio maxi spessore 3D",
    dimensions: { height: 100, width: 120, depth: 4.5 },
    framed: false,
    frameDetails: "",
    price: 3200,
    minPrice: 2800,
    currency: "EUR",
    status: "bottega",
    location: "Bottega - Parete Ovest",
    locationNotes: "Quadro di grandi dimensioni",
    notes: "Superficie fortemente materica che incorpora granelli di quarzo e sabbia marina.",
    certificateNumber: "CERT-2024-015",
    images: [],
    createdAt: "2024-04-05T16:10:00.000Z",
    updatedAt: "2024-04-05T16:10:00.000Z"
  },
  {
    id: "art-008",
    code: "OPV-008",
    title: "La quiete prima del temporale",
    artist: "Leonardo Vian",
    year: 2022,
    technique: "Olio su tavola antica",
    support: "Tavola di noce d'epoca restaurata",
    dimensions: { height: 50, width: 60, depth: 3 },
    framed: true,
    frameDetails: "Cornice d'epoca con doratura a foglia d'oro zecchino",
    price: 1400,
    minPrice: 1250,
    currency: "EUR",
    status: "venduto",
    location: "Collezione Privata - Firenze",
    locationNotes: "Certificato originale consegnato",
    buyerName: "Dott.ssa Anna De Luca",
    buyerContact: "Firenze - a.deluca@studiogiuridico.it",
    soldDate: "2023-11-20",
    notes: "Raffinata resa atmosferica dei cieli plumbei toscani con squarcio di sole sui campi.",
    certificateNumber: "CERT-2022-090",
    images: [],
    createdAt: "2022-10-14T12:00:00.000Z",
    updatedAt: "2023-11-20T18:00:00.000Z"
  },
  {
    id: "art-009",
    code: "OPV-009",
    title: "Forme nello Spazio II",
    artist: "Clara Bassi",
    year: 2023,
    technique: "Terracotta refrattaria e ossidi",
    support: "Base in legno massello d'olivo",
    dimensions: { height: 35, width: 30, depth: 25 },
    framed: false,
    frameDetails: "",
    price: 1600,
    minPrice: 1400,
    currency: "EUR",
    status: "in_corso",
    location: "Bottega - Banco Modellazione",
    locationNotes: "In attesa di rifinitura e cera protettiva",
    notes: "Studio tridimensionale sul rapporto tra pieni e vuoti ispirato alla bio-architettura.",
    certificateNumber: "CERT-2023-102",
    images: [],
    createdAt: "2023-12-01T10:30:00.000Z",
    updatedAt: "2024-01-10T11:00:00.000Z"
  },
  {
    id: "art-010",
    code: "OPV-010",
    title: "Luci Notturne sulla Darsena",
    artist: "Elena Moretti",
    year: 2024,
    technique: "Gouache e inchiostro di china",
    support: "Carta Arches 300g satinata",
    dimensions: { height: 45, width: 65, depth: 2 },
    framed: true,
    frameDetails: "Cornice minimalista in alluminio spazzolato grafite",
    price: 1100,
    minPrice: 950,
    currency: "EUR",
    status: "bottega",
    location: "Bottega - Parete Ingresso",
    locationNotes: "Vicino alla scrivania d'accoglienza",
    notes: "Contrasti cromatici tra i blu oltremare della notte e le luci riflesse nell'acqua del molo.",
    certificateNumber: "CERT-2024-022",
    images: [],
    createdAt: "2024-05-02T14:40:00.000Z",
    updatedAt: "2024-05-02T14:40:00.000Z"
  }
];

export const INITIAL_ARTWORKS: Artwork[] = [];
